### ISSUE TITLE
pgoutput-cli crashes with "object has no attribute 'cur'"

### ISSUE THREAD

**Issue by dewey** [gunnarmorling/pgoutput-cli#1]
Hey, I'm using the following command to run the Docker container:

```
docker run -it --rm gunnarmorling/pgoutput-cli pgoutput-cli --host=host.docker.internal --port=5432 --database=testing --user=postgres --password=testing --publication=url_filtered --slot=test_slot
```

After using an insert statement it's crashing every time with the stack trace below.

**Postgres**

```
services:
  postgres-testing:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_PASSWORD=testing
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
```

**psql**

```
testing=# CREATE TABLE url (
  id                BIGSERIAL PRIMARY KEY,
  url         		TEXT DEFAULT NULL,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  should_replicate  BOOL NOT NULL,
  last_changed_at	TIMESTAMP NOT NULL
);

testing=# CREATE PUBLICATION url_filtered FOR TABLE url (
    id,
        url,
    created_at,
    updated_at,
    should_replicate,
    last_changed_at
) WHERE (last_changed_at >= updated_at);
CREATE PUBLICATION
testing=# CREATE  UNIQUE INDEX url_replica_identity ON url (id,last_changed_at,updated_at);
ALTER TABLE url REPLICA IDENTITY USING INDEX url_replica_identity;
CREATE INDEX
ALTER TABLE
testing=# SELECT * FROM pg_create_logical_replication_slot('test_slot', 'pgoutput');
 slot_name |    lsn
-----------+-----------
 test_slot | 0/19C58F8
(1 row)

testing=# insert into url(id,should_replicate,last_changed_at)values(1,true,now());
INSERT 0 1
testing=#
```

After the last insert statement pgoutput-cli crashes like this:

```
~|⇒ docker run -it --rm gunnarmorling/pgoutput-cli pgoutput-cli --host=host.docker.internal --port=5432 --database=testing --user=postgres --password=testing --publication=url_filtered --slot=test_slot
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pypgoutput/reader.py", line 332, in __next__
    return next(self.transformed_msgs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypgoutput/reader.py", line 189, in transform_raw
    yield self.process_insert(message=msg, transaction=transaction_metadata)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypgoutput/reader.py", line 264, in process_insert
    after=self.table_models[relation_id](**after).dict(),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DynamicSchemaModel_16390
url
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pgoutput-cli", line 64, in <module>
    main(sys.argv[1:])
  File "/usr/bin/pgoutput-cli", line 58, in main
    for message in cdc_reader:
  File "/usr/local/lib/python3.12/site-packages/pypgoutput/reader.py", line 334, in __next__
    self.stop()
  File "/usr/local/lib/python3.12/site-packages/pypgoutput/reader.py", line 156, in stop
    self.extractor.close()
  File "/usr/local/lib/python3.12/site-packages/pypgoutput/reader.py", line 367, in close
    self.cur.close()
    ^^^^^^^^
AttributeError: 'ExtractRaw' object has no attribute 'cur'
```

The output sounds a bit like some nil value isn't checked somehow?

Let me know if I can provide more debug information.

Thanks!

**Comment by brunomgalmeida** [comment]
Can you try with 
>     "pydantic==1.9.0"
